### ISSUE TITLE
gosecret-cli

### ISSUE THREAD

**Issue by gwilton** [Cimpress-MCP/gosecret#3]
Hello,

Currently trying to use gosecret with consul.

The README installation instructions say "and install the CLI with go install from the gosecret-cli directory." There is no gosecret-cli any more. I guess "gosecret" is now the cli as well?

Thanks,
Wilton

**Comment by ryanbreen** [comment]
Yes, good catch.  I'll fix the docs.  Sorry about that!

**Comment by cleung2010** [comment]
The godoc URL is also broken. It should be http://godoc.org/github.com/Cimpress-MCP/gosecret

**Comment by ryanbreen** [comment]
Somehow it took me 3 commits, but I believe these issues are addressed.  Thanks!
